### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by SanAngeloMike** [demystifyfp/FsTweet#4]
I was following the instructions on page 13 (using the full downloaded boilerplate, rather than the file content specified in the text). I get the following error no whether I do Run, Build, or Clean:

λ forge fake Build

C:\Users\Mike\Documents\fsharp\FsTweet\packages\FAKE\tools\FAKE.exe Build
C:\Users\Mike\AppData\Local\Temp\kudutemp already exists.
C:\Users\Mike\AppData\Local\Temp\kudutarget already exists.
Deleting contents of C:\Users\Mike\AppData\Local\Temp\kudutemp
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FakeLib>.$Fake.Azure.Kudu' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Mike\AppData\Local\Temp\kudutemp\FsTweet.Db.Migrations.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at Fake.FileHelper.CleanDir@267-1.Invoke(String file) in D:\code\fake\src\app\FakeLib\FileHelper.fs:line 270
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Fake.FileHelper.CleanDir(String path) in D:\code\fake\src\app\FakeLib\FileHelper.fs:line 267
   at <StartupCode$FakeLib>.$Fake.Azure.Kudu..cctor() in D:\code\fake\src\app\FakeLib\AzureKudu.fs:line 26
   --- End of inner exception stack trace ---
   at Fake.Azure.Kudu.get_deploymentTemp()
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Fake.FSIHelper.runScriptCached@315.Invoke(Unit unitVar0) in D:\code\fake\src\app\FakeLib\FSIHelper.fs:line 323

Error while running 'C:\Users\Mike\Documents\fsharp\FsTweet\packages\FAKE\tools\FAKE.exe' with args: Build

**Comment by demystifyfp** [comment]
Hi @SanAngeloMike. Will check and revert at the earliest. Thanks for informing.

**Comment by SanAngeloMike** [comment]
thanks

**Comment by demystifyfp** [comment]
Hi @SanAngeloMike,

Are you using this boilerplate from this repository https://github.com/demystifyfp/FsTweetBoilerplate?

From the stack trace, I guess it is using the build script from the completed codebase (https://github.com/demystifyfp/FsTweet)?

**Comment by SanAngeloMike** [comment]
Yes, I am. I thought that there might be an issue there, but I assumed
since the build script came with the source code that they would be
compatible.

It would be good to have a completed repository with a working build script
so that, when your users get to a stuck point (as is inevitable when
following long scripts) they can check the completed code and solve the
problems themselves. This should reduce your workload and give you a code
base to answer questions from.

Also, I got a little confused when I saw a message talking about using git
bash. I am using Cmder, as the book says. I hope that's not an issue.

I really want to work my way thru your book but I have given up for now.

**Comment by SanAngeloMike** [comment]
Thanks for getting back to me so soon, btw.

**Comment by demystifyfp** [comment]
Hi @SanAngeloMike,

I am sorry for the inconvenience. Let me help you to overcome this.

I've tried to reproduce this issue. Here are the steps that I did (as per the instructions in the book)
* Cloned the boilerplate from here https://github.com/demystifyfp/FsTweetBoilerplate
* Ran `forge paket restore` and then `forge fake Run` 
* Application started running as expected. 

I am not sure about what is the root cause here. From the stack trace, I am seeing "Kudu" is getting executed but it is not a part of the `FsTweetBoilerplate` build script. It'd be helpful if you can provide the steps to reproduce.

> It would be good to have a completed repository with a working build script
so that, when your users get to a stuck point (as is inevitable when
following long scripts) they can check the completed code and solve the
problems themselves. This should reduce your workload and give you a code
base to answer questions from.

I agree with you. As you mentioned, to keep track of the changes, in the [FsTweet](https://github.com/demystifyfp/FsTweet) repository you can find the [Tags](https://github.com/demystifyfp/FsTweet/releases) associated with each logic steps and the final code base is in the `master` repository. 

> I really want to work my way thru your book but I have given up for now.

It's really sad to know this. Let me know how I can help you ?
